
stages:
  Data_Ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - data/input_data/magic04.data 
      - src/data_ingestion.py
    outs:
      - data/plots
      - data/raw


  Data_Preprocessing:
    cmd: python src/data_preprocessing.py
    deps: 
      - data/raw
      - src/data_preprocessing.py
    outs:
      - data/split_data


  Model Training:
    cmd: python src/train.py
    deps: 
      - data/split_data
      - src/train.py
    outs:
      - models/


  Model Evaluation:
    cmd: python src/evaluate.py
    deps: 
      - data/split_data
      - models/
      - src/evaluate.py
    metrics:
      - data/metrics/evaluation_results.json