
stages:
  Data_Ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - datasets/magic04.data 
      - src/data_ingestion.py
    outs:
      - data/plots
      - data/raw


  Data_Scaling:
    cmd: python src/data_scaling.py
    deps: 
      - data/raw
      - src/data_scaling.py
    outs:
      - split_data


  K-NearestNeighbors:
    cmd: python src/Models/knn.py
    deps: 
      - split_data
      - src/Models/knn.py
    outs:
      - knn_model.pkl
    
    metrics:
      - knn_metrics.json


  Naive_Bayes:
    cmd: python src/Models/naive_bayes.py
    deps: 
      - split_data
      - src/Models/naive_bayes.py
    outs:
      - nb_model.pkl
    
    metrics:
      - nb_metrics.json


  Logistic_Regression:
    cmd: python src/Models/LR.py
    deps: 
      - split_data
      - src/Models/LR.py
    outs:
      - lr_model.pkl

    metrics:
      - lr_metrics.json
        
        
  Support_Vector_Machine:
    cmd: python src/Models/SVM.py
    deps: 
      - split_data
      - src/Models/SVM.py
    outs:
      - svm_model.pkl

    metrics:
      - svm_metrics.json


 